steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-west2-docker.pkg.dev/devt-394612/react-docker-gcr-example-docker-repo/react-docker-gcr-image:tag1', '--build-arg', 'REACT_APP_TEST_VALUE=$_REACT_APP_TEST_VALUE', '.' ]
images:
  - 'us-west2-docker.pkg.dev/devt-394612/react-docker-gcr-example-docker-repo/react-docker-gcr-image:tag1'
